name: Document-PSModule (by PSModule)
description: Build documentation for a PowerShell module.
author: PSModule
branding:
  icon: package
  color: gray-dark

inputs:
  Name:
    description: Name of the module to process.
    required: false
  Path:
    description: Path to the folder where the modules are located.
    required: false
    default: src
  ModulesOutputPath:
    description: Path to the folder where the built modules are outputted.
    required: false
    default: outputs/modules
  ModuleArtifactName:
    description: Name of the module artifact to upload.
    required: false
    default: module
  DocsOutputPath:
    description: Path to the folder where the built docs are outputted.
    required: false
    default: outputs/docs
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Download module artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ModuleArtifactName }}
        path: ${{ inputs.ModulesOutputPath }}

    - name: Document-PSModule
      uses: PSModule/GitHub-Script@v1
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
        GITHUB_ACTION_INPUT_Path: ${{ inputs.Path }}
        GITHUB_ACTION_INPUT_ModulesOutputPath: ${{ inputs.ModulesOutputPath }}
        GITHUB_ACTION_INPUT_DocsOutputPath: ${{ inputs.DocsOutputPath }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        Script: |
          # Build-PSModuleDocumentation
          ${{ github.action_path }}\scripts\main.ps1
