name: Document-PSModule (by PSModule)
description: Build documentation for a PowerShell module.
author: PSModule
branding:
  icon: package
  color: gray-dark

inputs:
  Name:
    description: Name of the module to process.
    required: false
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/Install-PSModuleHelpers@v1

    - name: Document-PSModule
      shell: pwsh
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
      working-directory: ${{ inputs.WorkingDirectory }}
      run: |
        # Build-PSModuleDocumentation
        ${{ github.action_path }}/scripts/main.ps1
