name: Document-PSModule (by PSModule)
description: Build documentation for a PowerShell module.
author: PSModule
branding:
  icon: package
  color: gray-dark

inputs:
  Name:
    description: Name of the module to process.
    required: false
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Document-PSModule
      shell: pwsh
      env:
        GITHUB_ACTION_INPUT_Name: ${{ inputs.Name }}
      working-directory: ${{ inputs.WorkingDirectory }}
      run: |
        # Build-PSModuleDocumentation
        ${{ github.action_path }}/scripts/main.ps1
